name: Deploy NFN Field Book Production

on:
  # Run this workflow on push to production-release tag (via chatops)
  push:
    tags:
      - production-release

jobs:
  build:
    name: Build production
    uses: zooniverse/ci-cd/.github/workflows/npm_build.yaml@main
    with:
      commit_id: ${{ github.sha }}
      node_version: '16.x'
      output: 'build'
      script: 'build'
  deploy:
    name: Deploy production
    uses: zooniverse/ci-cd/.github/workflows/deploy_static.yaml@main
    needs: build
    with:
      source: 'build'
      target: 'field-book.notesfromnature.org'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}
  slack_notification:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Build production / build
      status: ${{ needs.deploy.result }}
      title: 'NFN Field Book Production deploy complete'
      title_link: 'https://field-book.notesfromnature.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
